apiVersion: v1
kind: Secret
metadata:  
  name: secret-from-file
type: Opaque
data:
  username: dGVzdA==
stringData:
  config.yaml: |
   password: notDecoded  

# the secrets have to be base64 encoded for data