apiVersion: v1
kind: Pod
metadata:
  name: network-tools
spec:
  containers:
  - name: network-tools
    image: jonlabelle/network-tools
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]