apiVersion: v1
kind: Pod
metadata:
  name: secret-test
spec:
  containers:
    - name: secret-test
      image: ubuntu
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
        # Define the environment variable
        - name: username
          valueFrom:
            secretKeyRef:
              name: testsecret
              key: username

# kubectl exec  --stdin --tty config-test -- bash
# echo $username